# Generated by Django 2.2.4 on 2019-08-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190819_1705'),
        ('users', '0002_auto_20190819_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='base.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Cleaner')]),
        ),
    ]
